### ISSUE TITLE
When using .toBeSortedBy() with 'descending: true', to assert against an object which is sorted in ascending order,  "Expected" message is incorrect.

### ISSUE THREAD

**Issue by FatlirT** [P-Copley/jest-sorted#30]
![Screenshot 2024-02-17 201738](https://github.com/P-Copley/jest-sorted/assets/68887876/5e5cb1b8-8e31-4c99-ab8a-2a60e2d58308)

In the test featured in the picture, the objects are in ascending order.
When `descending: true`, the assertion fails, which is what we expect, but the second `Expected` message is incorrect, stating: `Expected 5 to be before 10` even though we would expect 10 to be before 5 in Descending order.

I tested the 3 other combinations of the ordering of the data and the descending flag, and they didn't exhibit any unexpected behaviour, i,e:

When the objects are in ascending order and  `descending: false`, the assertion passes, as we expect.

When the objects are in descending order and  `descending: true`, the assertion passes, as we expect.

When the objects are in descending order and  `descending: false`, the assertion fails, but with a correct `Expected` message, as we would expect.

**Comment by FatlirT** [comment]
`coerce` flag has no effect.

**Comment by FatlirT** [comment]
My bad That is the correct output,

**Comment by P-Copley** [comment]
Thanks @FatlirT, this does indeed look like the wrong message.

I'll take a look when I get a sec but in the meantime if you feel like contributing feel free to open a PR 😁 

Cheers for flagging it 👍
